// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://truzqzseexnazaspsttd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRydXpxenNlZXhuYXphc3BzdHRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NDc2OTgsImV4cCI6MjA2MTUyMzY5OH0.pclp4LoQ-WcSliu9srEX0iiGQ1kI95UWYMm48beUfQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);